language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO_VERSION=1.4.8
  - DJANGO_VERSION=1.5.4
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script:
  - cd testproject
  - python manage.py test
matrix:
  exclude:
    - python: 3.3
      env: DJANGO_VERSION=1.4.8