language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.4.20
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.7
  - DJANGO=Django==1.8
install:
  - pip install $DJANGO
  - pip install -e .
  - pip install -r testproject/requirements_travis.txt
script:
  - python testproject/manage.py test docopt_example
  - coverage run --source=django_docopt_command,testproject/docopt_example testproject/manage.py test docopt_example
  - coverage report
after_success:
  - coveralls
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.7
    - python: 2.6
      env: DJANGO=Django==1.8
    - python: 3.3
      env: DJANGO=Django==1.4.20
    - python: 3.4
      env: DJANGO=Django==1.4.20
    - python: pypy
      env: DJANGO=Django==1.4.20
    - python: pypy
      env: DJANGO=Django==1.5.12
    - python: pypy
      env: DJANGO=Django==1.6.11
    - python: pypy
      env: DJANGO=Django==1.8
