language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.8
  - DJANGO=Django==1.5.4
  - DJANGO=https://www.djangoproject.com/download/1.6b4/tarball/
install:
  - pip install $DJANGO
  - python setup.py install
  - coverage run --source=django_docopt_command,docopt_example manage.py test
  - coverage report -m
script:
  - cd testproject
  - python manage.py test
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.4.8