language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.12
  - DJANGO=Django==1.5.7
  - DJANGO=Django==1.6.4
  - DJANGO=https://www.djangoproject.com/download/1.7b3/tarball/
install:
  - pip install $DJANGO
  - python setup.py install
  - pip install -r testproject/requirements_travis.txt
script:
  - cd testproject
  - python manage.py test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.7b3/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.12
