language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
env:
  - DJANGO=Django==1.4.19
  - DJANGO=Django==1.5.12
  - DJANGO=Django==1.6.10
  - DJANGO=Django==1.7.4
  - DJANGO=https://www.djangoproject.com/download/1.8a1/tarball/
install:
  - pip install $DJANGO
  - python setup.py install
  - pip install -r testproject/requirements_travis.txt
script:
  - cd testproject
  - python manage.py test docopt_example
  - coverage run --source=django_docopt_command,docopt_example manage.py test docopt_example
  - coverage report
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
after_success:
  - coveralls
  - cd ..
  - covio
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7.4
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.8a1/tarball/
    - python: 3.3
      env: DJANGO=Django==1.4.19
    - python: 3.4
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.4.19
    - python: pypy
      env: DJANGO=Django==1.5.12
    - python: pypy
      env: DJANGO=Django==1.6.10
